version: '3.7'
services:
#    restaurant_rabbitmq:
#        container_name: restaurant_rabbitmq
#        image: rabbitmq:management-alpine
#        hostname: my-rabbit
#        ports:
#            - 5672:5672
#            - 15672:15672

    app:
        build: app

    restaurant_nginx:
        container_name: restaurant_nginx
        build: nginx
        ports:
            - 5004:5004
        depends_on:
            - app
