version: '3.7'
services:
    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:management-alpine
        hostname: my-rabbit
        ports:
            - 5672:5672
            - 15672:15672

    app:
        build: app
        environment: 
            HOSTNAME: my-rabbit

    nginx:
        container_name: nginx
        build: nginx
        ports:
            - 5001:5001
        depends_on:
            - app
