version: '3.7'
services:
#    delivery_rabbitmq:
#        container_name: delivery_rabbitmq
#        image: rabbitmq:management-alpine
#        ports:
#            - 5672:5672
#            - 15672:15672

    app:
        build: app

    delivery_nginx:
        container_name: delivery_nginx
        build: nginx
        ports:
            - 5005:5005
        depends_on:
            - app
